### ISSUE TITLE
MathType for the new TinyMCE

### ISSUE THREAD

**Issue by Nenuial** [wiris/moodle-tinymce_tiny_mce_wiris#82]
This is not really an issue, but more of a question, please excuse me!

I am wondering if you have plans to offer a MathType for the new TinyMCE that became the default in Moodle 4.1?

Thank you in advance for any information you can offer on this topic!

**Comment by jguillen-at-wiris** [comment]
Hi Nenuial, thanks for your question.

You can address your doubts through our contact page:
https://www.wiris.com/en/contact-us/

We are already working on our TinyMCE6 compatibility for Moodle 4.1 & Moodle 4.2, which we believe it will be ready during Q2 2023 (around april), probably matching Moodle's next release.

I will close this thread. Should you be facing any specific issue regarding this topic, please, feel free to reopen it.
Otherwise, you can find us on the link shared above if you come with new questions.

Have a nice day!
